// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.33.1
// source: status/MatchHud.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "frc4765.proto.status";

export enum MatchPhase {
  PRE_MATCH = 0,
  AUTONOMOUS = 1,
  TRANSITION = 2,
  SHIFT1 = 3,
  SHIFT2 = 4,
  SHIFT3 = 5,
  SHIFT4 = 6,
  ENDGAME = 7,
  POST_MATCH = 8,
  UNRECOGNIZED = -1,
}

export function matchPhaseFromJSON(object: any): MatchPhase {
  switch (object) {
    case 0:
    case "PRE_MATCH":
      return MatchPhase.PRE_MATCH;
    case 1:
    case "AUTONOMOUS":
      return MatchPhase.AUTONOMOUS;
    case 2:
    case "TRANSITION":
      return MatchPhase.TRANSITION;
    case 3:
    case "SHIFT1":
      return MatchPhase.SHIFT1;
    case 4:
    case "SHIFT2":
      return MatchPhase.SHIFT2;
    case 5:
    case "SHIFT3":
      return MatchPhase.SHIFT3;
    case 6:
    case "SHIFT4":
      return MatchPhase.SHIFT4;
    case 7:
    case "ENDGAME":
      return MatchPhase.ENDGAME;
    case 8:
    case "POST_MATCH":
      return MatchPhase.POST_MATCH;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MatchPhase.UNRECOGNIZED;
  }
}

export function matchPhaseToJSON(object: MatchPhase): string {
  switch (object) {
    case MatchPhase.PRE_MATCH:
      return "PRE_MATCH";
    case MatchPhase.AUTONOMOUS:
      return "AUTONOMOUS";
    case MatchPhase.TRANSITION:
      return "TRANSITION";
    case MatchPhase.SHIFT1:
      return "SHIFT1";
    case MatchPhase.SHIFT2:
      return "SHIFT2";
    case MatchPhase.SHIFT3:
      return "SHIFT3";
    case MatchPhase.SHIFT4:
      return "SHIFT4";
    case MatchPhase.ENDGAME:
      return "ENDGAME";
    case MatchPhase.POST_MATCH:
      return "POST_MATCH";
    case MatchPhase.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum HubStatus {
  HUB_NONE = 0,
  HUB_BOTH = 1,
  HUB_ACTIVE = 2,
  HUB_WARNING = 3,
  HUB_INACTIVE = 4,
  UNRECOGNIZED = -1,
}

export function hubStatusFromJSON(object: any): HubStatus {
  switch (object) {
    case 0:
    case "HUB_NONE":
      return HubStatus.HUB_NONE;
    case 1:
    case "HUB_BOTH":
      return HubStatus.HUB_BOTH;
    case 2:
    case "HUB_ACTIVE":
      return HubStatus.HUB_ACTIVE;
    case 3:
    case "HUB_WARNING":
      return HubStatus.HUB_WARNING;
    case 4:
    case "HUB_INACTIVE":
      return HubStatus.HUB_INACTIVE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return HubStatus.UNRECOGNIZED;
  }
}

export function hubStatusToJSON(object: HubStatus): string {
  switch (object) {
    case HubStatus.HUB_NONE:
      return "HUB_NONE";
    case HubStatus.HUB_BOTH:
      return "HUB_BOTH";
    case HubStatus.HUB_ACTIVE:
      return "HUB_ACTIVE";
    case HubStatus.HUB_WARNING:
      return "HUB_WARNING";
    case HubStatus.HUB_INACTIVE:
      return "HUB_INACTIVE";
    case HubStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum HeaderColor {
  HEADER_HIDDEN = 0,
  HEADER_GREEN = 1,
  HEADER_YELLOW = 2,
  HEADER_PURPLE = 3,
  UNRECOGNIZED = -1,
}

export function headerColorFromJSON(object: any): HeaderColor {
  switch (object) {
    case 0:
    case "HEADER_HIDDEN":
      return HeaderColor.HEADER_HIDDEN;
    case 1:
    case "HEADER_GREEN":
      return HeaderColor.HEADER_GREEN;
    case 2:
    case "HEADER_YELLOW":
      return HeaderColor.HEADER_YELLOW;
    case 3:
    case "HEADER_PURPLE":
      return HeaderColor.HEADER_PURPLE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return HeaderColor.UNRECOGNIZED;
  }
}

export function headerColorToJSON(object: HeaderColor): string {
  switch (object) {
    case HeaderColor.HEADER_HIDDEN:
      return "HEADER_HIDDEN";
    case HeaderColor.HEADER_GREEN:
      return "HEADER_GREEN";
    case HeaderColor.HEADER_YELLOW:
      return "HEADER_YELLOW";
    case HeaderColor.HEADER_PURPLE:
      return "HEADER_PURPLE";
    case HeaderColor.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface MatchHudState {
  seq: string;
  robotTimeUs: string;
  connected: boolean;
  isRedAlliance: boolean;
  enabled: boolean;
  autonomous: boolean;
  gameSpecificMessage: string;
  matchPhase: MatchPhase;
  hubStatus: HubStatus;
  headerColor: HeaderColor;
  totalTimeRemainingS: number;
  periodTimeRemainingS: number;
  shiftTimeRemainingS: number;
  shiftTimeWithBufferS: number;
  bufferRemainingS: number;
  showShiftIndicator: boolean;
  showBuffer: boolean;
  robotPoseXM: number;
  robotPoseYM: number;
  robotHeadingRad: number;
  robotPoseValid: boolean;
  autoAlignActive: boolean;
  autoAlignDistanceM: number;
  autoAlignReady: boolean;
  driverOverride: boolean;
  cameraTopic: string;
}

function createBaseMatchHudState(): MatchHudState {
  return {
    seq: "0",
    robotTimeUs: "0",
    connected: false,
    isRedAlliance: false,
    enabled: false,
    autonomous: false,
    gameSpecificMessage: "",
    matchPhase: 0,
    hubStatus: 0,
    headerColor: 0,
    totalTimeRemainingS: 0,
    periodTimeRemainingS: 0,
    shiftTimeRemainingS: 0,
    shiftTimeWithBufferS: 0,
    bufferRemainingS: 0,
    showShiftIndicator: false,
    showBuffer: false,
    robotPoseXM: 0,
    robotPoseYM: 0,
    robotHeadingRad: 0,
    robotPoseValid: false,
    autoAlignActive: false,
    autoAlignDistanceM: 0,
    autoAlignReady: false,
    driverOverride: false,
    cameraTopic: "",
  };
}

export const MatchHudState: MessageFns<MatchHudState> = {
  encode(message: MatchHudState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seq !== "0") {
      writer.uint32(8).uint64(message.seq);
    }
    if (message.robotTimeUs !== "0") {
      writer.uint32(16).uint64(message.robotTimeUs);
    }
    if (message.connected === true) {
      writer.uint32(80).bool(message.connected);
    }
    if (message.isRedAlliance === true) {
      writer.uint32(88).bool(message.isRedAlliance);
    }
    if (message.enabled === true) {
      writer.uint32(96).bool(message.enabled);
    }
    if (message.autonomous === true) {
      writer.uint32(104).bool(message.autonomous);
    }
    if (message.gameSpecificMessage !== "") {
      writer.uint32(114).string(message.gameSpecificMessage);
    }
    if (message.matchPhase !== 0) {
      writer.uint32(160).int32(message.matchPhase);
    }
    if (message.hubStatus !== 0) {
      writer.uint32(168).int32(message.hubStatus);
    }
    if (message.headerColor !== 0) {
      writer.uint32(176).int32(message.headerColor);
    }
    if (message.totalTimeRemainingS !== 0) {
      writer.uint32(245).float(message.totalTimeRemainingS);
    }
    if (message.periodTimeRemainingS !== 0) {
      writer.uint32(253).float(message.periodTimeRemainingS);
    }
    if (message.shiftTimeRemainingS !== 0) {
      writer.uint32(261).float(message.shiftTimeRemainingS);
    }
    if (message.shiftTimeWithBufferS !== 0) {
      writer.uint32(269).float(message.shiftTimeWithBufferS);
    }
    if (message.bufferRemainingS !== 0) {
      writer.uint32(277).float(message.bufferRemainingS);
    }
    if (message.showShiftIndicator === true) {
      writer.uint32(280).bool(message.showShiftIndicator);
    }
    if (message.showBuffer === true) {
      writer.uint32(288).bool(message.showBuffer);
    }
    if (message.robotPoseXM !== 0) {
      writer.uint32(325).float(message.robotPoseXM);
    }
    if (message.robotPoseYM !== 0) {
      writer.uint32(333).float(message.robotPoseYM);
    }
    if (message.robotHeadingRad !== 0) {
      writer.uint32(341).float(message.robotHeadingRad);
    }
    if (message.robotPoseValid === true) {
      writer.uint32(344).bool(message.robotPoseValid);
    }
    if (message.autoAlignActive === true) {
      writer.uint32(400).bool(message.autoAlignActive);
    }
    if (message.autoAlignDistanceM !== 0) {
      writer.uint32(413).float(message.autoAlignDistanceM);
    }
    if (message.autoAlignReady === true) {
      writer.uint32(416).bool(message.autoAlignReady);
    }
    if (message.driverOverride === true) {
      writer.uint32(424).bool(message.driverOverride);
    }
    if (message.cameraTopic !== "") {
      writer.uint32(482).string(message.cameraTopic);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MatchHudState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMatchHudState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seq = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.robotTimeUs = reader.uint64().toString();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.connected = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.isRedAlliance = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.autonomous = reader.bool();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.gameSpecificMessage = reader.string();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.matchPhase = reader.int32() as any;
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.hubStatus = reader.int32() as any;
          continue;
        }
        case 22: {
          if (tag !== 176) {
            break;
          }

          message.headerColor = reader.int32() as any;
          continue;
        }
        case 30: {
          if (tag !== 245) {
            break;
          }

          message.totalTimeRemainingS = reader.float();
          continue;
        }
        case 31: {
          if (tag !== 253) {
            break;
          }

          message.periodTimeRemainingS = reader.float();
          continue;
        }
        case 32: {
          if (tag !== 261) {
            break;
          }

          message.shiftTimeRemainingS = reader.float();
          continue;
        }
        case 33: {
          if (tag !== 269) {
            break;
          }

          message.shiftTimeWithBufferS = reader.float();
          continue;
        }
        case 34: {
          if (tag !== 277) {
            break;
          }

          message.bufferRemainingS = reader.float();
          continue;
        }
        case 35: {
          if (tag !== 280) {
            break;
          }

          message.showShiftIndicator = reader.bool();
          continue;
        }
        case 36: {
          if (tag !== 288) {
            break;
          }

          message.showBuffer = reader.bool();
          continue;
        }
        case 40: {
          if (tag !== 325) {
            break;
          }

          message.robotPoseXM = reader.float();
          continue;
        }
        case 41: {
          if (tag !== 333) {
            break;
          }

          message.robotPoseYM = reader.float();
          continue;
        }
        case 42: {
          if (tag !== 341) {
            break;
          }

          message.robotHeadingRad = reader.float();
          continue;
        }
        case 43: {
          if (tag !== 344) {
            break;
          }

          message.robotPoseValid = reader.bool();
          continue;
        }
        case 50: {
          if (tag !== 400) {
            break;
          }

          message.autoAlignActive = reader.bool();
          continue;
        }
        case 51: {
          if (tag !== 413) {
            break;
          }

          message.autoAlignDistanceM = reader.float();
          continue;
        }
        case 52: {
          if (tag !== 416) {
            break;
          }

          message.autoAlignReady = reader.bool();
          continue;
        }
        case 53: {
          if (tag !== 424) {
            break;
          }

          message.driverOverride = reader.bool();
          continue;
        }
        case 60: {
          if (tag !== 482) {
            break;
          }

          message.cameraTopic = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MatchHudState {
    return {
      seq: isSet(object.seq) ? globalThis.String(object.seq) : "0",
      robotTimeUs: isSet(object.robotTimeUs) ? globalThis.String(object.robotTimeUs) : "0",
      connected: isSet(object.connected) ? globalThis.Boolean(object.connected) : false,
      isRedAlliance: isSet(object.isRedAlliance) ? globalThis.Boolean(object.isRedAlliance) : false,
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      autonomous: isSet(object.autonomous) ? globalThis.Boolean(object.autonomous) : false,
      gameSpecificMessage: isSet(object.gameSpecificMessage) ? globalThis.String(object.gameSpecificMessage) : "",
      matchPhase: isSet(object.matchPhase) ? matchPhaseFromJSON(object.matchPhase) : 0,
      hubStatus: isSet(object.hubStatus) ? hubStatusFromJSON(object.hubStatus) : 0,
      headerColor: isSet(object.headerColor) ? headerColorFromJSON(object.headerColor) : 0,
      totalTimeRemainingS: isSet(object.totalTimeRemainingS) ? globalThis.Number(object.totalTimeRemainingS) : 0,
      periodTimeRemainingS: isSet(object.periodTimeRemainingS) ? globalThis.Number(object.periodTimeRemainingS) : 0,
      shiftTimeRemainingS: isSet(object.shiftTimeRemainingS) ? globalThis.Number(object.shiftTimeRemainingS) : 0,
      shiftTimeWithBufferS: isSet(object.shiftTimeWithBufferS) ? globalThis.Number(object.shiftTimeWithBufferS) : 0,
      bufferRemainingS: isSet(object.bufferRemainingS) ? globalThis.Number(object.bufferRemainingS) : 0,
      showShiftIndicator: isSet(object.showShiftIndicator) ? globalThis.Boolean(object.showShiftIndicator) : false,
      showBuffer: isSet(object.showBuffer) ? globalThis.Boolean(object.showBuffer) : false,
      robotPoseXM: isSet(object.robotPoseXM) ? globalThis.Number(object.robotPoseXM) : 0,
      robotPoseYM: isSet(object.robotPoseYM) ? globalThis.Number(object.robotPoseYM) : 0,
      robotHeadingRad: isSet(object.robotHeadingRad) ? globalThis.Number(object.robotHeadingRad) : 0,
      robotPoseValid: isSet(object.robotPoseValid) ? globalThis.Boolean(object.robotPoseValid) : false,
      autoAlignActive: isSet(object.autoAlignActive) ? globalThis.Boolean(object.autoAlignActive) : false,
      autoAlignDistanceM: isSet(object.autoAlignDistanceM) ? globalThis.Number(object.autoAlignDistanceM) : 0,
      autoAlignReady: isSet(object.autoAlignReady) ? globalThis.Boolean(object.autoAlignReady) : false,
      driverOverride: isSet(object.driverOverride) ? globalThis.Boolean(object.driverOverride) : false,
      cameraTopic: isSet(object.cameraTopic) ? globalThis.String(object.cameraTopic) : "",
    };
  },

  toJSON(message: MatchHudState): unknown {
    const obj: any = {};
    if (message.seq !== "0") {
      obj.seq = message.seq;
    }
    if (message.robotTimeUs !== "0") {
      obj.robotTimeUs = message.robotTimeUs;
    }
    if (message.connected === true) {
      obj.connected = message.connected;
    }
    if (message.isRedAlliance === true) {
      obj.isRedAlliance = message.isRedAlliance;
    }
    if (message.enabled === true) {
      obj.enabled = message.enabled;
    }
    if (message.autonomous === true) {
      obj.autonomous = message.autonomous;
    }
    if (message.gameSpecificMessage !== "") {
      obj.gameSpecificMessage = message.gameSpecificMessage;
    }
    if (message.matchPhase !== 0) {
      obj.matchPhase = matchPhaseToJSON(message.matchPhase);
    }
    if (message.hubStatus !== 0) {
      obj.hubStatus = hubStatusToJSON(message.hubStatus);
    }
    if (message.headerColor !== 0) {
      obj.headerColor = headerColorToJSON(message.headerColor);
    }
    if (message.totalTimeRemainingS !== 0) {
      obj.totalTimeRemainingS = message.totalTimeRemainingS;
    }
    if (message.periodTimeRemainingS !== 0) {
      obj.periodTimeRemainingS = message.periodTimeRemainingS;
    }
    if (message.shiftTimeRemainingS !== 0) {
      obj.shiftTimeRemainingS = message.shiftTimeRemainingS;
    }
    if (message.shiftTimeWithBufferS !== 0) {
      obj.shiftTimeWithBufferS = message.shiftTimeWithBufferS;
    }
    if (message.bufferRemainingS !== 0) {
      obj.bufferRemainingS = message.bufferRemainingS;
    }
    if (message.showShiftIndicator === true) {
      obj.showShiftIndicator = message.showShiftIndicator;
    }
    if (message.showBuffer === true) {
      obj.showBuffer = message.showBuffer;
    }
    if (message.robotPoseXM !== 0) {
      obj.robotPoseXM = message.robotPoseXM;
    }
    if (message.robotPoseYM !== 0) {
      obj.robotPoseYM = message.robotPoseYM;
    }
    if (message.robotHeadingRad !== 0) {
      obj.robotHeadingRad = message.robotHeadingRad;
    }
    if (message.robotPoseValid === true) {
      obj.robotPoseValid = message.robotPoseValid;
    }
    if (message.autoAlignActive === true) {
      obj.autoAlignActive = message.autoAlignActive;
    }
    if (message.autoAlignDistanceM !== 0) {
      obj.autoAlignDistanceM = message.autoAlignDistanceM;
    }
    if (message.autoAlignReady === true) {
      obj.autoAlignReady = message.autoAlignReady;
    }
    if (message.driverOverride === true) {
      obj.driverOverride = message.driverOverride;
    }
    if (message.cameraTopic !== "") {
      obj.cameraTopic = message.cameraTopic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MatchHudState>, I>>(base?: I): MatchHudState {
    return MatchHudState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MatchHudState>, I>>(object: I): MatchHudState {
    const message = createBaseMatchHudState();
    message.seq = object.seq ?? "0";
    message.robotTimeUs = object.robotTimeUs ?? "0";
    message.connected = object.connected ?? false;
    message.isRedAlliance = object.isRedAlliance ?? false;
    message.enabled = object.enabled ?? false;
    message.autonomous = object.autonomous ?? false;
    message.gameSpecificMessage = object.gameSpecificMessage ?? "";
    message.matchPhase = object.matchPhase ?? 0;
    message.hubStatus = object.hubStatus ?? 0;
    message.headerColor = object.headerColor ?? 0;
    message.totalTimeRemainingS = object.totalTimeRemainingS ?? 0;
    message.periodTimeRemainingS = object.periodTimeRemainingS ?? 0;
    message.shiftTimeRemainingS = object.shiftTimeRemainingS ?? 0;
    message.shiftTimeWithBufferS = object.shiftTimeWithBufferS ?? 0;
    message.bufferRemainingS = object.bufferRemainingS ?? 0;
    message.showShiftIndicator = object.showShiftIndicator ?? false;
    message.showBuffer = object.showBuffer ?? false;
    message.robotPoseXM = object.robotPoseXM ?? 0;
    message.robotPoseYM = object.robotPoseYM ?? 0;
    message.robotHeadingRad = object.robotHeadingRad ?? 0;
    message.robotPoseValid = object.robotPoseValid ?? false;
    message.autoAlignActive = object.autoAlignActive ?? false;
    message.autoAlignDistanceM = object.autoAlignDistanceM ?? 0;
    message.autoAlignReady = object.autoAlignReady ?? false;
    message.driverOverride = object.driverOverride ?? false;
    message.cameraTopic = object.cameraTopic ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
